name: Deploy to staging server.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup authentication
        run: |
          SSHPATH="$HOME/.ssh"
          mkdir -p $SSHPATH
          echo "$KEY" > "$SSHPATH/key"
          chmod 600 "$SSHPATH/key"
        env:
          KEY: ${{ secrets.SSH_KEY }}

      # Runs a set of commands using the runners shell
      - name: Deploy
        run: rsync -az --delete -e 'ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no -p 22' $GITHUB_WORKSPACE/ hackco@68.162.241.27:/home/hackco/domains/new.hack3.co/public_html
